
## Container Image Versions
export KONG_VERSION=3.10.0.1
export POSTGRES_VERSION=16.9
export PROMETHEUS_VERSION=v3.4.0
export GRAFANA_VERSION=12.0.1
export GRAFANA_LOKI_VERSION=3.5.0
export GRAFANA_TEMPO_VERSION=2.7.2
export MEMCACHED_VERSION=1.6.38
export OTEL_COLLECTOR_VERSION=0.126.0
export FLUENTBIT_VERSION=4.0.2


export DECK_TLS_SKIP_VERIFY=true
export DECK_KONG_ADDR=http://localhost:8001

export KONG_LICENSE_FILE=~/.kong-license-data/license.json