global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kong'
    static_configs:
      - targets: ['kong-gateway:8001']
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]
  - job_name: 'fluentbit'
    static_configs:
      - targets: [ 'fluent-bit:2021' ]