receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resource:
    attributes:
      - action: upsert
        key: service.name
        value: kong-dev

exporters:
  otlphttp:
    endpoint: http://loki:3100/otlp
    encoding: json
  debug: {} 

service:
  telemetry:
    metrics:
      address: ":8888"
    logs:
      level: "debug"

  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - resource
      exporters:
        - otlphttp
        - debug
